package com.healthinsurance.policy.mapper;

import com.healthinsurance.policy.dto.request.*;
import com.healthinsurance.policy.dto.response.*;
import com.healthinsurance.policy.entity.*;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

@Mapper(componentModel = "spring")
public interface PolicyMapper {

    // Request -> Entity
    @Mapping(target = "status", ignore = true)
    @Mapping(target = "policyNumber", ignore = true) // Generated by Service Layer
    Policy toEntity(PolicyCreateRequest request);

    PolicyMember toEntity(PolicyMemberRequest request);
    PolicyCoverage toEntity(PolicyCoverageRequest request);
    PolicyBeneficiary toEntity(PolicyBeneficiaryRequest request);

    // Entity -> Response
    PolicyResponse toResponse(Policy entity);
    PolicyMemberResponse toResponse(PolicyMember entity);
    PolicyCoverageResponse toResponse(PolicyCoverage entity);
    PolicyBeneficiaryResponse toResponse(PolicyBeneficiary entity);
    @Mapping(target = "changeData", ignore = true)
    @Mapping(target = "policyId", source = "policy.policyId")
    @Mapping(target = "policyNumber", source = "policy.policyNumber")
    PolicyEndorsementResponse toResponse(PolicyEndorsement entity);

    @Mapping(target = "policyId", source = "policy.policyId")
    @Mapping(target = "policyNumber", source = "policy.policyNumber")
    PolicyCancellationResponse toResponse(PolicyCancellation entity);

    @Mapping(target = "policyId", source = "policy.policyId")
    @Mapping(target = "policyNumber", source = "policy.policyNumber")
    PolicyRenewalResponse toResponse(PolicyRenewal entity);
}