global:
  scrape_interval: 10s
  evaluation_interval: 10s

rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          service: 'api-gateway'
          env: 'dev'

  - job_name: 'service-discovery'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8761']
        labels:
          service: 'service-discovery'
          env: 'dev'

  - job_name: 'config-server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8888']
        labels:
          service: 'config-server'
          env: 'dev'

  - job_name: 'identity-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8081']
        labels:
          service: 'identity-service'
          env: 'dev'

  - job_name: 'customer-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8082']
        labels:
          service: 'customer-service'
          env: 'dev'

  - job_name: 'product-plan-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8083']
        labels:
          service: 'product-plan-service'
          env: 'dev'

  - job_name: 'quotation-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8084']
        labels:
          service: 'quotation-service'
          env: 'dev'

  - job_name: 'risk-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8085']
        labels:
          service: 'risk-service'
          env: 'dev'

  - job_name: 'underwriting-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8086']
        labels:
          service: 'underwriting-service'
          env: 'dev'

  - job_name: 'policy-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8087']
        labels:
          service: 'policy-service'
          env: 'dev'

  - job_name: 'premium-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8088']
        labels:
          service: 'premium-service'
          env: 'dev'

  - job_name: 'payment-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8089']
        labels:
          service: 'payment-service'
          env: 'dev'

  - job_name: 'provider-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8090']
        labels:
          service: 'provider-service'
          env: 'dev'

  - job_name: 'claims-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8092']
        labels:
          service: 'claims-service'
          env: 'dev'

  - job_name: 'document-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8094']
        labels:
          service: 'document-service'
          env: 'dev'

  - job_name: 'notification-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8095']
        labels:
          service: 'notification-service'
          env: 'dev'

  - job_name: 'reporting-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8096']
        labels:
          service: 'reporting-service'
          env: 'dev'